// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_dist
NumericMatrix cpp_dist(NumericMatrix D, IntegerMatrix T, NumericMatrix C, int ncol, double threshold);
RcppExport SEXP cidr_cpp_dist(SEXP DSEXP, SEXP TSEXP, SEXP CSEXP, SEXP ncolSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dist(D, T, C, ncol, threshold));
    return rcpp_result_gen;
END_RCPP
}
