# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dist <- function(D, T, C, ncol, threshold) {
    .Call('cidr_cpp_dist', PACKAGE = 'cidr', D, T, C, ncol, threshold)
}

